---
- name: Create a VM from a template
  hosts: localhost
  gather_facts: no
  collections:
    - community.vmware
  become: no
  roles:
    - role: create-vm
      vars:
        vms:
          - name: testvm01
            ipaddr: 10.0.0.142
            netmask: 255.255.255.0
            dns_domain: lan.stderr.at
            dns_servers:
              - 10.0.0.254
              - 8.8.8.8
            dns_suffix:
              - lan.stderr.at
              - stderr.at
          - name: testvm02
            ipaddr: 10.0.0.143
            netmask: 255.255.255.0
            memory_mb: 1024
            num_cpus: 1
            disk_size_gb: 20
            dns_domain: lan.stderr.at
            dns_servers:
              - 10.0.0.254
            dns_suffix:
              - lan.stderr.at
              - stderr.at
