---
- name: Destroy a vm
  hosts: localhost
  gather_facts: no
  become: no
  tasks:
  - name: Destroying vm {{ vmname }}
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      validate_certs: False
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      cluster: "{{ vcenter_cluster_name }}"
      name: "{{ vmname }}"
      datacenter: "{{ vcenter_datacenter }}"
      folder: "{{ vcenter_folder | default(omit) }}"
      state: absent
      force: yes
